# Generated by Django 4.0.5 on 2022-06-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='profileimg',
        ),
    ]
