# Generated by Django 4.0.5 on 2022-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='/Users/aaryman/Desktop/social_book/social_clone/static/images/resources/btm-baner-avatar.png', upload_to='profile_pictures'),
        ),
    ]
